/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.paypal.cookie.schema;  
@SuppressWarnings("all")
/** Log XPPP cookie. */
@org.apache.avro.specific.AvroGenerated
public class CookiePPLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CookiePPLog\",\"namespace\":\"com.paypal.cookie.schema\",\"doc\":\"Log XPPP cookie.\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"body\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long timestamp;
  @Deprecated public java.lang.CharSequence body;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CookiePPLog() {}

  /**
   * All-args constructor.
   */
  public CookiePPLog(java.lang.Long timestamp, java.lang.CharSequence body) {
    this.timestamp = timestamp;
    this.body = body;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return body;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: body = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /** Creates a new CookiePPLog RecordBuilder */
  public static com.paypal.cookie.schema.CookiePPLog.Builder newBuilder() {
    return new com.paypal.cookie.schema.CookiePPLog.Builder();
  }
  
  /** Creates a new CookiePPLog RecordBuilder by copying an existing Builder */
  public static com.paypal.cookie.schema.CookiePPLog.Builder newBuilder(com.paypal.cookie.schema.CookiePPLog.Builder other) {
    return new com.paypal.cookie.schema.CookiePPLog.Builder(other);
  }
  
  /** Creates a new CookiePPLog RecordBuilder by copying an existing CookiePPLog instance */
  public static com.paypal.cookie.schema.CookiePPLog.Builder newBuilder(com.paypal.cookie.schema.CookiePPLog other) {
    return new com.paypal.cookie.schema.CookiePPLog.Builder(other);
  }
  
  /**
   * RecordBuilder for CookiePPLog instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CookiePPLog>
    implements org.apache.avro.data.RecordBuilder<CookiePPLog> {

    private long timestamp;
    private java.lang.CharSequence body;

    /** Creates a new Builder */
    private Builder() {
      super(com.paypal.cookie.schema.CookiePPLog.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.paypal.cookie.schema.CookiePPLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CookiePPLog instance */
    private Builder(com.paypal.cookie.schema.CookiePPLog other) {
            super(com.paypal.cookie.schema.CookiePPLog.SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public com.paypal.cookie.schema.CookiePPLog.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'timestamp' field */
    public com.paypal.cookie.schema.CookiePPLog.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'body' field */
    public java.lang.CharSequence getBody() {
      return body;
    }
    
    /** Sets the value of the 'body' field */
    public com.paypal.cookie.schema.CookiePPLog.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.body = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'body' field has been set */
    public boolean hasBody() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'body' field */
    public com.paypal.cookie.schema.CookiePPLog.Builder clearBody() {
      body = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public CookiePPLog build() {
      try {
        CookiePPLog record = new CookiePPLog();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.body = fieldSetFlags()[1] ? this.body : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
